"use client";
import { FormEvent, useState } from "react";
import { clinic } from "@/lib/clinic";
import { Icon } from "./Icon";

export function AppointmentSearch() {
  const [submitted, setSubmitted] = useState(false);
  function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSubmitted(true); }
  return <section id="find-appointment" className="section-pad scroll-mt-8 bg-white"><div className="container-page grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="eyebrow">Find my appointment</p><h2 className="section-title">Check Your Upcoming Visit</h2><p className="mt-5 max-w-lg leading-7">Enter the phone number used when booking to view your current or upcoming appointment.</p><p className="mt-5 flex items-start gap-2 text-sm text-muted"><Icon name="shield" className="mt-0.5 h-5 w-5 shrink-0 text-dental"/>For privacy, only current and future appointments will be shown after secure integration is added.</p></div><div className="card p-6 sm:p-8"><form onSubmit={handleSubmit}><label htmlFor="appointment-phone" className="block text-sm font-bold text-navy">Phone number</label><p id="phone-help" className="mt-1 text-sm text-muted">Use the same number provided when you called the clinic.</p><div className="mt-4 flex flex-col gap-3 sm:flex-row"><input id="appointment-phone" name="phone" type="tel" autoComplete="tel" inputMode="tel" placeholder="0969 519 5316" aria-describedby="phone-help" required className="min-h-12 min-w-0 flex-1 rounded-lg border border-border px-4 text-base text-navy outline-none transition-shadow placeholder:text-[#8798a2] focus:border-dental focus:ring-4 focus:ring-dental/15"/><button type="submit" className="btn-primary shrink-0"><Icon name="calendar" className="h-5 w-5"/>Find My Appointment</button></div></form>{submitted && <div role="status" aria-live="polite" className="mt-5 rounded-lg border border-[#b9ddeb] bg-light-blue p-4 text-sm leading-6 text-navy"><strong className="block">Appointment search is coming soon.</strong>This preview does not search or send your phone number yet. For help now, please <a href={clinic.phoneHref} className="font-bold text-dental underline underline-offset-2">call the clinic</a>.</div>}</div></div></section>;
}
